/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */
import SFPRODISPLAYBOLD from './SFPRODISPLAYBOLD.woff';
import SFPRODISPLAYMEDIUM from './SFPRODISPLAYMEDIUM.woff';
import SFPRODISPLAYREGULAR from './SFPRODISPLAYREGULAR.woff';

export { SFPRODISPLAYBOLD, SFPRODISPLAYMEDIUM, SFPRODISPLAYREGULAR };
